- name: Install openvpn package
  pacman: name=openvpn state=present

# Copy VPN configs
- name: copy openvpn client config
  become: yes
  copy: src="openvpn/client.conf" 
        dest=/etc/openvpn/client.conf
  notify:
    - "Restart_Openvpn_Client"

- name: copy openvpn AirVpn client config
  become: yes
  copy: src="openvpn/airvpn_europe.conf" 
        dest=/etc/openvpn/airvpn_europe.conf
  notify:
    - "Restart_Openvpn_AirVpn"

# Start VPN clients
- name: Ensure openvpn is running
  become: yes
  service: name=openvpn@client state=started
  notify:
    - "Restart_Shorewall"

- name: Ensure Airvpn is running
  become: yes
  service: name=openvpn@airvpn_europe state=started
  notify:
    - "Restart_Shorewall"

- include: shorewall-integration.yml
- include: systemd-overrides.yml
