- name: decrypt secrets file
  include_vars: "secrets.yml"
  no_log: true

- name: Install openvpn package
  pacman: name=openvpn state=present

- name: create openvpn client config directory
  file:
    path: "/etc/openvpn/client/"
    owner: root
    group: root
    mode: 0600
    state: directory


# Copy Client VPN configs
- name: copy openvpn [{{item}}] client config
  become: yes
  copy: src="openvpn/{{item}}.conf"
        dest="/etc/openvpn/client/{{item}}.conf"
  notify:
    - "Restart_Openvpn_{{item}}"
  with_items:
  - walle
  - tz_rom


# TZ VPN config
- file:
    path: /etc/openvpn/tz_rom
    owner: root
    group: root
    mode: 0600
    state: directory

- name: copy Tz_Rom client secrets
  become: yes
  template: src="openvpn/tz_rom-{{ item }}.j2"
        dest="/etc/openvpn/tz_rom/{{ item }}"
  with_items:
  - pass.txt
  - ca.crt
  notify:
    - "Restart_Openvpn_tz_rom"

# Shorewall/SystemD integration
- include: shorewall-integration.yml
- include: systemd-overrides.yml connection="{{item}}"
  with_items:
  - walle
  - tz_rom
