# Generates /var/lib/dhcpcd/dhcpcd-tun1.info when connecting
- name: copy openvpn OpenVPN gateway script
  sudo: yes
  copy: src="../../files/openvpn/save_gateway.rb" 
        dest=/etc/openvpn/save_gateway.rb

# Used by Shorewall to determine VPN gateway
- shell: stat -c %a /var/lib/dhcpcd/dhcpcd-tun1.info
  register: dhcpcd_tun1
  changed_when: False
  always_run: yes

- name: create tun1 lease info file 
  file: path=/var/lib/dhcpcd/dhcpcd-tun1.info owner=root group=root mode=0664 state=touch
  when: dhcpcd_tun1.stdout != "664"

# Copy override Shorewall configs requiring Openvpn services
- name: copy shorewall service override configs
  sudo: yes
  copy: src="../../files/openvpn/systemd-overrides/shorewall-service-override.conf"
        dest=/etc/systemd/system/shorewall.service.d/override.conf
  notify:
    - "Restart_Shorewall"

