# Generates /var/lib/dhcpcd/dhcpcd-tun1.info when connecting
- name: copy openvpn OpenVPN gateway script
  become: yes
  copy: src="openvpn/save_gateway.rb"
        dest=/etc/openvpn/save_gateway.rb

# Copy override Shorewall configs requiring Openvpn services
- name: copy shorewall service override configs
  become: yes
  copy: src="openvpn/systemd-overrides/shorewall-service-override.conf"
        dest=/etc/systemd/system/shorewall.service.d/override.conf
  notify:
    - "Restart_Shorewall"
