# Copy systemd overrides
- name: create openvpn [{{connection}}] override directory
  file:
    path: "/etc/systemd/system/openvpn-client@{{connection}}.service.d"
    owner: root
    group: root
    mode: 0644
    state: directory

- name: copy openvpn [{{connection}}] systemd override 
  become: yes
  copy: src="openvpn/systemd-overrides/{{connection}}-service-override.conf" 
        dest="/etc/systemd/system/openvpn-client@{{connection}}.service.d/override.conf"
  notify:
    - "Reload_Systemd"
