# Copy systemd overrides

- name: copy openvpn systemd client override 
  sudo: yes
  copy: src="../../files/openvpn/systemd-overrides/client-service-override.conf" 
        dest=/etc/systemd/system/openvpn@client.service.d/override.conf
  notify:
    - "Restart_Openvpn_Client"

#- name: copy openvpn systemd airvpn override 
#  sudo: yes
#  copy: src="../../files/openvpn/systemd-overrides/airvpn-service-override.conf" 
#        dest=/etc/systemd/system/openvpn@airvpn.service.d/override.conf
#  notify:
#    - "Restart_Openvpn_AirVpn"
