kind: Service
apiVersion: v1
metadata:
  name: radarr-service
  namespace: default
  labels:
    app: radarr
spec:
  selector:
    app: radarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: admin
      name: admin
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr-lb
  namespace: default
spec:
  rules:
  - host: radarr.k8s.home.masgras.us
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr-service
          servicePort: admin
