- name: ensure openvpn is running
  sudo: yes
  service: name=openvpn state=started

- name: copy openvpn server config
  sudo: yes
  copy: src=openvpn/server.conf dest=/etc/openvpn/server.conf
  notify:
    - "Restart_Openvpn"
