---
- name: "Restart_Dnsmasq"
  sudo: yes
  service: name=dnsmasq state=restarted

- name: "Restart_Hostapd"
  sudo: yes
  service: name=hostapd state=restarted

- name: "Restart_Shorewall"
  sudo: yes
  service: name=shorewall state=restarted

- name: "Restart_Ddclient"
  sudo: yes
  service: name=ddclient state=restarted

- name: "Restart_Openvpn"
  sudo: yes
  service: name=openvpn@client state=restarted
