---
- name: "Restart_Dnsmasq"
  sudo: yes
  service: name=dnsmasq state=restarted

- name: "Restart_Hostapd"
  sudo: yes
  service: name=hostapd state=restarted

- name: "Restart_Shorewall"
  sudo: yes
  service: name=shorewall state=restarted

- name: "Restart_Ddclient"
  sudo: yes
  service: name=ddclient state=restarted

- name: "Restart_Openvpn_Client"
  sudo: yes
  service: name=openvpn@client state=restarted

- name: "Restart_Openvpn_AirVpn"
  sudo: yes
  service: name=openvpn@airvpn_europe state=restarted

- name: "Restart_Netctl_eth1"
  sudo: yes
  raw: /usr/bin/netctl restart eth1-dhcp

- name: "Restart_Sshd"
  sudo: yes
  service: name=sshd state=restarted
