kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-certificates
  namespace: kube-system
  annotations:
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
