- name: decrypt secrets file
  include_vars: "secrets.yml"
  no_log: true

- name: copy authorized keys
  template: src=authorized_keys.j2 dest="/home/{{ ansible_ssh_user }}/.ssh/authorized_keys" mode=0400
