- name: Install ddclient package
  pacman: name=ddclient state=present

- name: Ensure ddclient is running
  sudo: yes
  service: name=ddclient state=started

- name: copy ddclient config
  sudo: yes
  copy: src=ddclient.conf dest=/etc/ddclient/ddclient.conf
  notify:
    - "Restart_Ddclient"
