- name: Install DNSmasq package
  pacman: name=dnsmasq state=present

- name: copy dnsmasq config
  become: yes
  copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  notify:
    - "Restart_Dnsmasq"

- name: Ensure DNSmasq is running
  become: yes
  service: name=dnsmasq state=started

