- name: Install hostapd package
  pacman: name=hostapd state=present

- name: Ensure hostapd is stopped
  become: yes
  service: name=hostapd state=stopped

- name: copy hostapd config
  become: yes
  copy: src=hostapd.conf dest=/etc/hostapd/hostapd.conf
  notify:
    - "Restart_Hostapd"
