---
- name : Install rsync 
  pacman: name=rsync state=present

- include: netctl-if.yml
- include: dnsmasq.yml
- include: hostapd.yml
- include: ip-forward.yml
- include: shorewall.yml
- include: ddclient.yml
- include: hosts.yml
- include: openvpn.yml
- include: dhcpcd.yml
