---
- name: pacman update
  become: yes
  pacman: update_cache=yes

- name : Install rsync 
  pacman: name=rsync state=present

- include: netctl-if.yml
- include: dnsmasq.yml
- include: hostapd.yml
- include: ip-forward.yml
- include: shorewall.yml
- include: ddclient.yml
- include: hosts.yml
- include: openvpn/openvpn.yml
- include: dhcpcd.yml
- include: ssh.yml
