- name: copy bridge interface config
  sudo: yes
  copy: src=br0 dest=/etc/netctl/br0

- shell: netctl is-enabled br0
  register: br0_enabled
  changed_when: False
  ignore_errors: True

- name: enable br0
  sudo: yes
  shell: netctl enable br0
  when: br0_enabled|failed
