# - name: pacman update
#   become: yes
#   pacman: update_cache=yes

- name : Install Shorewall Firewall package
  pacman: name=shorewall state=present

- name: sync shorewall configs
  become: yes
  synchronize: src=shorewall/ dest=/etc/shorewall/ archive=no
  notify:
    - "Restart_Shorewall"

- name: Ensure shorewall is enabled
  become: yes
  service: name=shorewall enabled=yes

- name: Ensure shorewall is running
  become: yes
  service: name=shorewall state=started

