- name: copy SSHD config
  sudo: yes
  copy: src=ssh/sshd_config dest=/etc/ssh/sshd_config
  notify:
    - "Restart_Sshd"

- name: copy SSH authorized_keys config
  sudo: yes
  copy: src=ssh/authorized_keys dest=/home/gmas/.ssh/authorized_keys mode=0400
