apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arm-exporter
  namespace: monitoring
  labels:
    k8s-app: arm-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: arm-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http
    interval: 30s
