apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-ingress-lb
  labels:
    k8s-app: traefik-ingress-lb
spec:
  jobLabel: k8s-app
  endpoints:
  - port: admin
    interval: 30s
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  namespaceSelector:
    matchNames:
    - kube-system
